version: '3.8'

services:
  db-DT:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      POSTGRES_DB: DTsistemas
      POSTGRES_USER: DTuser
      POSTGRES_PASSWORD: DTuser
      TZ: "America/Sao_Paulo"
    container_name: db-DT

# Web panel to see the database and it's contents
# Access it on http://localhost:8080
# First you need to add the server with the db-DT details

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - db-DT
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80

  manager:
    build:
      context: ./
      dockerfile: manager/Dockerfile
    command: >
      sh -c "python manager/app.py"
    ports:
      - 5095:5095
    depends_on:
      - db-DT
    container_name: manager

  collector:
    build:
      context: ./
      dockerfile: collector/Dockerfile
    command: >
      sh -c "python collector/app.py"
    ports:
      - 5096:5096
    environment:
      TZ: "America/Sao_Paulo"
      URL_MANAGER: "http://manager:5095"
      PYTHONUNBUFFERED: 1
    depends_on:
      - db-DT
      - manager
    container_name: collector