version: '3.8'

services:
  db-DT:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: DTsistemas
      POSTGRES_USER: DTuser
      POSTGRES_PASSWORD: DTuser
      TZ: "America/Sao_Paulo"
    container_name: db-DT
    volumes:
      -

  manager:
    build:
      context: ./
      dockerfile: Manager/Dockerfile
    command: >
      sh -c "python app.py"
    ports:
      - 5095:5095
    volumes:
      - .
    environment:

    depends_on:
      - db-DT
    container_name: manager

  collector:
    build:
      context: ./
      dockerfile: Collector/Dockerfile
    command: >
      sh -c "python app.py"
    ports:
      - 5096:5096
    volumes:
      - ./Collector
      - ./data/web:/vol/web
    environment:
      TZ: "America/Sao_Paulo"
      URL_MANAGER: "http://manager:5095"
      PYTHONUNBUFFERED: 1
    depends_on:
      - db-DT
      - Manager
    container_name: collector